name: Build docker image for consent-management-provider
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check-version:
    name: Check version
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    outputs:
      version: ${{ steps.version.outputs.content }}

    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Read version information
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./version.txt

      - name: Check if version does not yet exist
        id: compare
        uses: GuillaumeFalourd/assert-command-line-output@v2
        with:
          command_line: git tag -l ${{ steps.version.outputs.content }}
          assert_file_path: ./version.txt
          expected_result: FAILED

  build-and-push-image:
    name: Build and push image
    needs: check-version
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        id: install
        run: npm install

      - name: Read version information
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./version.txt

      - name: Build app
        id: build
        if: github.ref == 'refs/heads/master'
        run: npm run build

      - name: Log in to the Container registry
        id: login
        if: github.ref == 'refs/heads/master'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        if: github.ref == 'refs/heads/master'
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=${{ needs.check-version.outputs.version }}

      - name: Build and push Docker image
        id: build_push
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
