name: Build docker image for consent-management-provider
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check-version:
    name: Check version
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    outputs:
      version: ${{ steps.version.outputs.content }}

    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Read version information
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./version.txt

      - name: Check if version does not yet exist
        id: compare
        uses: GuillaumeFalourd/assert-command-line-output@v2
        with:
          command_line: git tag -l ${{ steps.version.outputs.content }}
          assert_file_path: ./version.txt
          expected_result: FAILED

  build-and-push-image:
    name: Build and push image
    needs: check-version
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        id: install
        run: npm install

      - name: Build app
        id: build
        run: npm run build

      - name: Test app
        id: test
        run: npm run ci
        env:
          HTTP_PORT: 3000
          HTTP_HOST: localhost:3000
          COOKIE_DOMAIN: localhost

      - name: Log in to the Container registry
        id: login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if PR
        uses: 8BitJonny/gh-get-current-pr@2.1.3
        id: pr

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=${{ steps.pr.outcome == 'success' && format('pr-{0}-build-{1}', steps.pr.outputs.number, github.run_number) || format('v{0}', needs.check-version.outputs.version) }}

      - name: Build and push Docker image
        id: build_push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
