name: Build docker image for consent-management-provider
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check-version:
    name: Check version
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    timeout-minutes: 30

    outputs:
      version: ${{ steps.package-version.outputs.current-version }}

    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        id: login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main

      - name: Check if version does not yet exist
        id: compare
        run: ./test_version.sh ghcr.io/${{ github.repository }}:${{format('v{0}', steps.package-version.outputs.current-version)}}

  build-and-push-image:
    name: Build and push image
    needs: check-version
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        id: install
        run: npm install

      - name: Build app
        id: build
        run: npm run build

      - name: Test app
        id: test
        run: npm run ci
        env:
          HTTP_PORT: 3000
          HTTP_HOST: localhost:3000
          COOKIE_DOMAIN: localhost
          CMP_ENABLED_SAMPLING_THRESHOLD_PERCENT: 100
          API_VERSION: v2

      - name: Install k6
        run: |
          curl https://github.com/loadimpact/k6/releases/download/v0.26.2/k6-v0.26.2-linux64.tar.gz -L | tar xvz --strip-components 1

      - name: Run local k6 test
        env:
          HTTP_PORT: 3000
          HTTP_HOST: localhost:3000
          COOKIE_DOMAIN: localhost
          CMP_ENABLED_SAMPLING_THRESHOLD_PERCENT: 100
          API_VERSION: v2
        run: |
          npm start & npx wait-on http://localhost:3000/health
          ./k6 run ./load_test/core.js --out json=results.json --vus 50 --iterations 1000

      - name: Upload performance test results
        uses: actions/upload-artifact@v3
        with:
          name: k6-report
          path: results.json

      - name: Log in to the Container registry
        id: login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=${{ github.ref == 'refs/heads/master' && format('v{0}', needs.check-version.outputs.version) || format('build-{0}', github.run_number) }}

      - name: Build and push Docker image
        id: build_push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
