name: Build docker image for consent-management-provider
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        id: install
        run: npm install

      - name: Test
        id: test
        run: npm test

      - uses: GuillaumeFalourd/assert-command-line-output@v2
        with:
          command_line: git tag -l ${{ steps.version.outputs.content }}
          assert_file_path: ./version.txt
          expected_result: FAILED

      - name: Build app
        id: build
        if: github.ref == 'refs/heads/master'
        run: npm run build

      - name: Log in to the Container registry
        id: login
        if: github.ref == 'refs/heads/master'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        if: github.ref == 'refs/heads/master'
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=${{ github.run_number }}

      - name: Build and push Docker image
        id: build_push
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
