name: DEV - Static Bucket

on:
  push:
    branches:
      - "develop"
      - "feature/*"
      - "release/*"
      - "hotfix/*"

jobs:
  deploy-dev:
    name: DEV - Deploy static assets to storage bucket
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        env:
          - config: .env.agf.dev
            bucket: consent-management-agf-v3-static

    steps:
      - id: node
        name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4

      - id: install
        name: Install dependencies
        run: yarn install --frozen-lockfile

      - id: lint
        name: Lint
        run: yarn lint

      - id: test
        name: Test (source)
        run: yarn ci

      - id: build-test
        name: Build (test)
        run: yarn build --config .env.test

      - id: test-dist
        name: Test (build)
        run: yarn ci-dist

      - id: build
        name: Build (dist)
        run: yarn build --config ${{ matrix.env.config }}

      - id: auth
        #if: github.ref == 'refs/heads/develop'
        uses: google-github-actions/auth@v2
        with:
          project_id: tv-insight-dev
          credentials_json: ${{ secrets.GCP_CMP_SA_KEY }}

      - id: upload
        #if: github.ref == 'refs/heads/develop'
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: dist
          project_id: tv-insight-dev
          destination: ${{ matrix.env.bucket }}
          parent: false
          predefinedAcl: publicRead
          process_gcloudignore: false
