name: Develop

on:
  push:
    branches:
      - "develop"
      - "feature/*"
      - "release/*"
      - "hotfix/*"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - id: hosts
        name: Add hosts to /etc/hosts
        run: |
            sudo echo "127.0.0.1 local.client.com" | sudo tee -a /etc/hosts
            sudo echo "127.0.0.1 local.consent.com" | sudo tee -a /etc/hosts

      - id: node
        name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - id: checkout
        name: Checkout repository
        uses: actions/checkout@v4

      - id: dependencies
        name: Install dependencies
        run: yarn install --frozen-lockfile

      - id: lint
        name: Lint
        run: yarn lint

      - id: test
        name: Test
        run: yarn ci
        env:
          CMP_ENABLED: true
          CONSENT_HOST: local.consent.com:3000
          CONSENT_PATH: /
          COOKIE_DOMAIN: local.consent.com
          CONSENT_COOKIE_NAME: consent-localhost
          TECH_COOKIE_NAME: xt-localhost
          TECH_COOKIE_MIN: 0
          CMP_ENABLED_SAMPLING_THRESHOLD_PERCENT: 100
          BANNER_TIMEOUT: 120000

  create-prerelease:
    name: Create Pre-Release
    needs: test
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write

    steps:
      - id: node
        name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - id: checkout
        name: Checkout repository
        uses: actions/checkout@v4

      - id: dependencies
        name: Install dependencies
        run: yarn install --frozen-lockfile

      - id: build
        name: Build templates
        run: yarn build

      - id: zip
        name: Zip templates
        run: zip -r -j templates.zip ./dist/*

      - id: snapshot
        name: Create snapshot tag
        run: |
          echo 'version=snapshot_${{ github.run_number }}' >> $GITHUB_OUTPUT

      - id: release
        name: Create release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.snapshot.outputs.version }}
          tag_name: ${{ steps.snapshot.outputs.version }}
          files: |
            templates.zip
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
