name: Build and test
on:
  push:
    branches:
      - "develop"
      - "feature/*"
      - "release/*"
      - "hotfix/*"
      - "force_error"

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    timeout-minutes: 30

    steps:
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        id: install
        run: yarn install

      - name: Lint
        id: lint
        run: yarn lint

      - name: Build app
        id: build
        run: yarn build
        env:
          BUILD_NUMBER: ${{ github.run_number }}

      - name: Test app
        id: test
        run: yarn ci
        env:
          HTTP_PORT: 3000
          HTTP_HOST: localhost:3000
          COOKIE_DOMAIN: localhost
          TECH_COOKIE_MIN: 0
          CMP_ENABLED_SAMPLING_THRESHOLD_PERCENT: 100
          CMP_DISABLED_CHANNEL_IDS: 1234,4321

      - name: Install k6
        run: |
          curl https://github.com/loadimpact/k6/releases/download/v0.26.2/k6-v0.26.2-linux64.tar.gz -L | tar xvz --strip-components 1

      - name: Run local k6 test
        id: local-k6
        env:
          HTTP_PORT: 3000
          HTTP_HOST: localhost:3000
          COOKIE_DOMAIN: localhost
          TECH_COOKIE_MIN: 0
          CMP_ENABLED_SAMPLING_THRESHOLD_PERCENT: 100
          CMP_DISABLED_CHANNEL_IDS: 1234,4321
        run: |
          yarn start & npx wait-on http://localhost:3000/health
          ./k6 run ./load_test/core.js --vus 50 --iterations 1000

      - name: Get latest version
        id: get-latest-version
        if: ${{ github.ref == 'refs/heads/develop' || github.ref == 'force_error' }}
        uses: actions-ecosystem/action-get-latest-tag@v1
        with:
          semver_only: true

      - name: Set snapshot tag
        id: set-snapshot-tag
        if: ${{ github.ref == 'refs/heads/develop' || github.ref == 'force_error' }}
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ steps.get-latest-version.outputs.tag }}_snapshot_${{ github.run_number }}',
              sha: context.sha
            })

      - name: Log in to container registry
        id: registry-login
        if: ${{ github.ref == 'refs/heads/develop' || github.ref == 'force_error' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for docker
        id: docker-meta
        if: ${{ github.ref == 'refs/heads/develop' || github.ref == 'force_error' }}
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=${{ steps.get-latest-version.outputs.tag }}_snapshot_${{ github.run_number }}

      - name: Build and push docker image
        id: docker-build-push
        if: ${{ github.ref == 'refs/heads/develop' || github.ref == 'force_error' }}
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.docker-meta.outputs.tags }}
          labels: ${{ steps.docker-meta.outputs.labels }}
