name: Build and test
on:
  push:
    branches:
      - "develop"
      - "feature/*"

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        id: install
        run: npm install

      - name: Lint
        id: lint
        run: npm run lint

      - name: Build app
        id: build
        run: npm run build

      - name: Test app
        id: test
        run: npm run ci
        env:
          HTTP_PORT: 3000
          HTTP_HOST: localhost:3000
          COOKIE_DOMAIN: localhost
          CMP_ENABLED_SAMPLING_THRESHOLD_PERCENT: 100
          API_VERSION: v2

      - name: Install k6
        run: |
          curl https://github.com/loadimpact/k6/releases/download/v0.26.2/k6-v0.26.2-linux64.tar.gz -L | tar xvz --strip-components 1

      - name: Run local k6 test
        env:
          HTTP_PORT: 3000
          HTTP_HOST: localhost:3000
          COOKIE_DOMAIN: localhost
          CMP_ENABLED_SAMPLING_THRESHOLD_PERCENT: 100
          API_VERSION: v2
        run: |
          npm start & npx wait-on http://localhost:3000/health
          ./k6 run ./load_test/core.js --vus 50 --iterations 1000
