name: Release
on:
  push:
    branches:
      - "!develop"
    tags:
      - "v*.*.*"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - id: node
        name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - id: checkout
        name: Checkout repository
        uses: actions/checkout@v4

      - id: dependencies
        name: Install dependencies
        run: yarn install --frozen-lockfile

      - id: lint
        name: Lint
        run: yarn lint

      - id: test
        name: Test
        run: yarn ci

  release:
    name: Create release
    needs: test
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - id: node
        name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - id: checkout
        name: Checkout repository
        uses: actions/checkout@v4

      - id: dependencies
        name: Install dependencies
        run: yarn install --frozen-lockfile

      - id: build
        name: Build
        run: yarn build --config .env.agf.dev

      - id: zip
        name: Zip templates
        run: zip -r -j templates-agf-prod.zip ./dist/*

      - id: release
        name: Create release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{  github.ref_name }}
          files: |
            templates-agf-prod.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
